package interfacegrafica;

import entidade.Aluno;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AlunoPO;

public class Principal extends javax.swing.JFrame {

    private ArrayList<Aluno> listaAlunos;
    private DefaultTableModel model;
    private AlunoPO alunoPO;
    File selectedFile;

    public Principal() {
        initComponents();
        alunoPO = new AlunoPO();
        model = (DefaultTableModel) table.getModel();
    }

//    public void preencherTabela(ArrayList<Aluno> listaAlunos) {
//        try {   
//            for(Aluno aluno : listaAlunos){
//                model.addRow(new Object[]{
//                    aluno.getMatricula(),
//                    aluno.getMatricula().getNomeDoCurso(),
//                    aluno.getNome(),
//                    aluno.getDisciplinas()});
//            }
//        } catch (Exception erro) {
//            JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + erro.getMessage());
//        }
//    }
    public void preencherTabela(Iterator conjunto) {
        try {
            while (conjunto.hasNext()) {
                Object[] linha = new Object[4];
                Aluno objetoAluno = (Aluno) conjunto.next();
                linha[0] = objetoAluno.getMatricula();
                linha[1] = objetoAluno.getMatricula().getNomeDoCurso();
                linha[2] = objetoAluno.getNome();
                linha[3] = objetoAluno.getDisciplinas();
                model.addRow(linha);

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + erro.getMessage());
        }
    }
    
        public File abrirArquivo() {
        JFileChooser arquivo = new JFileChooser();
        int res = arquivo.showOpenDialog(this);

        if (res == JFileChooser.APPROVE_OPTION) {
            try {
                return selectedFile = arquivo.getSelectedFile();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileCh = new javax.swing.JFileChooser();
        btnListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnListarArrayList = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnListarFila = new javax.swing.JButton();
        btnListarSet = new javax.swing.JButton();
        btnListarArvore = new javax.swing.JButton();
        btnListarPilha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnListar.setText("Sair");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Curso", "Nome", "Disciplinas"
            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane2.setViewportView(table);

        btnListarArrayList.setText("Listar ArrayList");
        btnListarArrayList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnListarArrayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArrayListActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnListarFila.setText("Listar Fila");
        btnListarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFilaActionPerformed(evt);
            }
        });

        btnListarSet.setText("Listar Set");
        btnListarSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSetActionPerformed(evt);
            }
        });

        btnListarArvore.setText("Listar Arvore");
        btnListarArvore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArvoreActionPerformed(evt);
            }
        });

        btnListarPilha.setText("Listar Pilha");
        btnListarPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPilhaActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar:");

        jRadioButton1.setText("Crescente");

        jRadioButton2.setText("Decrescente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarPilha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarArvore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarArrayList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarArrayList)
                    .addComponent(btnLimpar)
                    .addComponent(btnListarFila)
                    .addComponent(btnListarSet)
                    .addComponent(btnListarArvore)
                    .addComponent(btnListar)
                    .addComponent(btnListarPilha)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnListarArrayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArrayListActionPerformed
            try {
                abrirArquivo();
                Iterator urlarquivo = alunoPO.listarComArraylist(selectedFile.getAbsolutePath());
                preencherTabela(urlarquivo);
                //preencherTabela(listaAlunos);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
    }//GEN-LAST:event_btnListarArrayListActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        model.setNumRows(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnListarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFilaActionPerformed
            try {
                abrirArquivo();
                Iterator urlarquivo = alunoPO.listarComFila(selectedFile.getAbsolutePath());
                preencherTabela(urlarquivo);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
    }//GEN-LAST:event_btnListarFilaActionPerformed

    private void btnListarSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSetActionPerformed
                 try {
                abrirArquivo();
                Iterator urlarquivo = alunoPO.listarComSet(selectedFile.getAbsolutePath());
                preencherTabela(urlarquivo);
                //preencherTabela(listaAlunos);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
    }//GEN-LAST:event_btnListarSetActionPerformed

    private void btnListarArvoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArvoreActionPerformed
            try {
                abrirArquivo();
                Iterator urlarquivo = alunoPO.listarComArvore(selectedFile.getAbsolutePath());
                preencherTabela(urlarquivo);
                //preencherTabela(listaAlunos);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
    }//GEN-LAST:event_btnListarArvoreActionPerformed

    private void btnListarPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPilhaActionPerformed
                    try {
                abrirArquivo();
                Iterator urlarquivo = alunoPO.listarComPilha(selectedFile.getAbsolutePath());
                preencherTabela(urlarquivo);
                //preencherTabela(listaAlunos);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir o arquivo" + ex.getMessage());
            }
    }//GEN-LAST:event_btnListarPilhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarArrayList;
    private javax.swing.JButton btnListarArvore;
    private javax.swing.JButton btnListarFila;
    private javax.swing.JButton btnListarPilha;
    private javax.swing.JButton btnListarSet;
    private javax.swing.JFileChooser fileCh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
